cmd/cert-csi/main.go
App name typo fix
|https://github.com/dell/csm/issues/938|
=> App Name typo

example-certify-config.yaml
Updating config file for cert-csi.
|https://github.com/dell/csm/issues/914|
=> Config file update

pkg/testcore/runner/perf-runner.go
gosec issue fix
| https://github.com/dell/csm/issues/885 |
=> gosec issue fix

go.mod, go.sum
Update logrus library
| https://github.com/dell/csm/issues/885 |
=> Update logrus library

pkg/utils/e2e_reporting.go
Printing passed test cases for K8s E2E tests 
| https://github.com/dell/csm/issues/1140 |
=> Printing passed test cases in the report 

pkg/k8sclient/resources/pvc/pvc.go, pkg/k8sclient/resources/statefulset/sts.go
Updated `ResourceRequirements` to `VolumeResourceRequirements` present in module `k8s.io/api`
| https://github.com/dell/csm/issues/1091 |
=> Go module fix

cmd/cert-csi/main.go
A few sentences describing the overall goals of the pull request's commits.
|https://github.com/dell/csm/issues/1091|
=> Version bump up for CSM 1.10

cmd/cert-csi/main.go
Version update
|https://github.com/dell/csm/issues/1280|
=> Version update

cmd/cert-csi/main.go
version-1.5.0.
|https://github.com/dell/csm/issues/1221|
=> version-1.5.0

pkg/k8sclient/resources/pod/pod.go, pkg/k8sclient/resources/pv/pv.go, pkg/k8sclient/resources/sc/sc.go, pkg/k8sclient/resources/statefulset/sts.go, pkg/k8sclient/resources/volumegroupsnapshot/vgs.go, pkg/k8sclient/resources/volumesnapshot/v1/snap.go, pkg/k8sclient/resources/volumesnapshot/v1beta1/snap.go, pkg/k8sclient/resources/volumesnapshotcontent/v1/content.go, pkg/k8sclient/resources/volumesnapshotcontent/v1beta1/content.go, pkg/observer/va.go, pkg/observer/va_alt.go, pkg/plotter/plotter.go, pkg/store/store_test.go, pkg/testcore/suites/functional-suites.go, pkg/testcore/suites/perf-suites.go, pkg/utils/k8s_utils.go
=> Fix linter warnings

cmd/cert-csi/main.go
cert-csi version bump up to 1.6.0
| https://github.com/dell/csm/issues/1435
Cert-csi was executed successfully
=> cert-csi version bump up

pkg/k8sclient/core.go, pkg/k8sclient/resources/pod/pod.go
CertCSI is hitting a failure in MultiAttachSuite (MAS).
| https://github.com/dell/csm/issues/1665|
Cert csi on ocp environment: 
powerflex: 
[powerflex_cert_csi_on_ocp.txt](https://github.com/user-attachments/files/18330965/powerflex_cert_csi_on_ocp.txt)
powerscale: 
[powerscale_cert_csi_on_ocp.txt](https://github.com/user-attachments/files/18330967/powerscale_cert_csi_on_ocp.txt)
unity: 
[unity_cert_csi_on_ocp.txt](https://github.com/user-attachments/files/18330971/unity_cert_csi_on_ocp.txt)
Cert csi on k8senvironment: 
powerflex: …
=> Fixing  cert-csi failure for Multiattach Test

pkg/cmd/certifycmd.go, pkg/testcore/suites/functional-suites.go
Powerflex ephemeral cert-csi test was failing with error volume Name not found
|  https://github.com/dell/csm/issues/1664|
Cert-csi on ocp environment:
Driver : Powerflex  
[powerflex_cert_csi_on_ocp.txt](https://github.com/user-attachments/files/18330680/powerflex_cert_csi_on_ocp.txt)
Driver : Unity 
[unity_cert_csi_on_ocp.txt](https://github.com/user-attachments/files/18330685/unity_cert_csi_on_ocp.txt)
Driver: Powerscale
[powerscale_cert_csi_on_ocp.txt](https://github.com/user-attachments/files/18330693/powerscale_cert_csi_on_ocp.txt)
Cert-csi on k8s environment:
Driver : …
=> Fixing  cert-csi failure for powerflex ephemeral test

pkg/testcore/suites/perf-suites_test.go
Merging volume expansion suite run tests
=> Multi driver capacity tracking vol expansion run

pkg/k8sclient/resources/volumesnapshot/v1/snap_test.go, pkg/k8sclient/resources/volumesnapshot/v1beta1/snap_test.go
A few sentences describing the overall goals of the pull request's commits.
| |
=> UT coverage

pkg/testcore/suites/common/common_test.go, pkg/testcore/suites/mockutils/mockutils_test.go
Increase Code coverage for cert-csi/pkg/testcore/suites/mockutils and cert-csi/pkg/testcore/suites/common
| |
=> Increase code coverage 

pkg/k8sclient/resources/pod/pod.go, pkg/k8sclient/resources/pod/pod_test.go
Increased code coverage to 85.3%
=> increased k8sclient/resources/pod unit test code coverage 

pkg/k8sclient/core.go, pkg/k8sclient/core_test.go, pkg/k8sclient/resources/pod/pod.go
Resolved an issue where the cert-csi test was not passing. Added extra coverage for lost coverage from fix.
=> Fix ut testing

README.md
Fix for Broken link in Read me page of cert-csi
| https://github.com/dell/csm/issues/1901 |
=> Fix for Broken link in Read me page of cert-csi

cmd/cert-csi/main.go
Increment CLI version
|https://github.com/dell/csm/issues/1896 |
=> Increment CLI version
